version: "3.9"

services:
  ollama:
    image: ollama/ollama:0.4.9
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

  indexer:
    build:
      context: .
      dockerfile: indexer/Dockerfile
    env_file: .env
    volumes:
      - docs-data:/app/docs        # maps to DOCS_DIR inside ingest watcher
      - vectorstore-data:/app/vectorstore
    depends_on:
      - ollama
    restart: unless-stopped

  backend:
    working_dir: /workspace
    image: python:3.12-slim
    command: bash -lc "pip install --no-cache-dir -r backend/requirements.txt && python -m chainlit run backend/app.py"
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./:/workspace
      - vectorstore-data:/vectorstore
    depends_on:
      - indexer
      - ollama
    restart: unless-stopped

volumes:
  docs-data:
  vectorstore-data:
  ollama-data:
