name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
          cache-dependency-path: poetry.lock

      - name: Bootstrap environment
        run: |
          if [ -f Makefile ] || [ -f makefile ]; then
            make bootstrap POETRY_INSTALL_ARGS="--with dev"
          else
            echo "Makefile missing; falling back to explicit bootstrap"
            python3 -m venv .venv --without-pip
            source .venv/bin/activate
            curl -sSL https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
            python /tmp/get-pip.py --force-reinstall
            python -m pip install --upgrade pip setuptools wheel poetry
            poetry install --no-root --with dev
          fi

      - name: Run tests
        run: |
          if [ -f Makefile ] || [ -f makefile ]; then
            make test-fast
          else
            echo "Makefile missing; running direct pytest"
            source .venv/bin/activate
            poetry run pytest -m "not slow" -q
          fi

