name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  verify:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Python version (avoid pyenv shim confusion)
        run: |
          pyenv shell system || true
          python3 --version

      - name: Bootstrap environment via Makefile
        run: |
          make bootstrap

      - name: Format check
        run: |
          make format

      - name: Run tests
        run: |
          make test
